//Working with "optional chaining"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
function getCustomer(id) {
    return id === 0 ? null : { birthday: new Date() };
}
var customer = getCustomer(1);
//Optional property access operator
console.log(customer === null || customer === void 0 ? void 0 : customer.birthday.getFullYear());
//optional element access operator
//customer?.[0]
//optional call
var log = null;
log === null || log === void 0 ? void 0 : log('a');
console.log(log);
